/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TripsNewRouteImport } from './routes/trips.new'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as StoreTripIdRouteImport } from './routes/store.$tripId'
import { Route as ProductCodeRouteImport } from './routes/product.$code'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as TripsTripIdIndexRouteImport } from './routes/trips.$tripId.index'
import { Route as StoreTripIdIndexRouteImport } from './routes/store.$tripId.index'
import { Route as TripsTripIdSwipeRouteImport } from './routes/trips.$tripId.swipe'
import { Route as TripsTripIdPreparingRouteImport } from './routes/trips.$tripId.preparing'
import { Route as TripsTripIdPackingRouteImport } from './routes/trips.$tripId.packing'
import { Route as TripsTripIdEditRouteImport } from './routes/trips.$tripId.edit'
import { Route as StoreTripIdScanRouteImport } from './routes/store.$tripId.scan'
import { Route as StoreTripIdNavRouteImport } from './routes/store.$tripId.nav'
import { Route as StoreTripIdArRouteImport } from './routes/store.$tripId.ar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsNewRoute = TripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreTripIdRoute = StoreTripIdRouteImport.update({
  id: '/store/$tripId',
  path: '/store/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCodeRoute = ProductCodeRouteImport.update({
  id: '/product/$code',
  path: '/product/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdIndexRoute = TripsTripIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TripsTripIdRoute,
} as any)
const StoreTripIdIndexRoute = StoreTripIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreTripIdRoute,
} as any)
const TripsTripIdSwipeRoute = TripsTripIdSwipeRouteImport.update({
  id: '/swipe',
  path: '/swipe',
  getParentRoute: () => TripsTripIdRoute,
} as any)
const TripsTripIdPreparingRoute = TripsTripIdPreparingRouteImport.update({
  id: '/preparing',
  path: '/preparing',
  getParentRoute: () => TripsTripIdRoute,
} as any)
const TripsTripIdPackingRoute = TripsTripIdPackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => TripsTripIdRoute,
} as any)
const TripsTripIdEditRoute = TripsTripIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TripsTripIdRoute,
} as any)
const StoreTripIdScanRoute = StoreTripIdScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => StoreTripIdRoute,
} as any)
const StoreTripIdNavRoute = StoreTripIdNavRouteImport.update({
  id: '/nav',
  path: '/nav',
  getParentRoute: () => StoreTripIdRoute,
} as any)
const StoreTripIdArRoute = StoreTripIdArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => StoreTripIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/product/$code': typeof ProductCodeRoute
  '/store/$tripId': typeof StoreTripIdRouteWithChildren
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/trips/': typeof TripsIndexRoute
  '/store/$tripId/ar': typeof StoreTripIdArRoute
  '/store/$tripId/nav': typeof StoreTripIdNavRoute
  '/store/$tripId/scan': typeof StoreTripIdScanRoute
  '/trips/$tripId/edit': typeof TripsTripIdEditRoute
  '/trips/$tripId/packing': typeof TripsTripIdPackingRoute
  '/trips/$tripId/preparing': typeof TripsTripIdPreparingRoute
  '/trips/$tripId/swipe': typeof TripsTripIdSwipeRoute
  '/store/$tripId/': typeof StoreTripIdIndexRoute
  '/trips/$tripId/': typeof TripsTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/product/$code': typeof ProductCodeRoute
  '/trips/new': typeof TripsNewRoute
  '/trips': typeof TripsIndexRoute
  '/store/$tripId/ar': typeof StoreTripIdArRoute
  '/store/$tripId/nav': typeof StoreTripIdNavRoute
  '/store/$tripId/scan': typeof StoreTripIdScanRoute
  '/trips/$tripId/edit': typeof TripsTripIdEditRoute
  '/trips/$tripId/packing': typeof TripsTripIdPackingRoute
  '/trips/$tripId/preparing': typeof TripsTripIdPreparingRoute
  '/trips/$tripId/swipe': typeof TripsTripIdSwipeRoute
  '/store/$tripId': typeof StoreTripIdIndexRoute
  '/trips/$tripId': typeof TripsTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/product/$code': typeof ProductCodeRoute
  '/store/$tripId': typeof StoreTripIdRouteWithChildren
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/trips/': typeof TripsIndexRoute
  '/store/$tripId/ar': typeof StoreTripIdArRoute
  '/store/$tripId/nav': typeof StoreTripIdNavRoute
  '/store/$tripId/scan': typeof StoreTripIdScanRoute
  '/trips/$tripId/edit': typeof TripsTripIdEditRoute
  '/trips/$tripId/packing': typeof TripsTripIdPackingRoute
  '/trips/$tripId/preparing': typeof TripsTripIdPreparingRoute
  '/trips/$tripId/swipe': typeof TripsTripIdSwipeRoute
  '/store/$tripId/': typeof StoreTripIdIndexRoute
  '/trips/$tripId/': typeof TripsTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/product/$code'
    | '/store/$tripId'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/'
    | '/store/$tripId/ar'
    | '/store/$tripId/nav'
    | '/store/$tripId/scan'
    | '/trips/$tripId/edit'
    | '/trips/$tripId/packing'
    | '/trips/$tripId/preparing'
    | '/trips/$tripId/swipe'
    | '/store/$tripId/'
    | '/trips/$tripId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/product/$code'
    | '/trips/new'
    | '/trips'
    | '/store/$tripId/ar'
    | '/store/$tripId/nav'
    | '/store/$tripId/scan'
    | '/trips/$tripId/edit'
    | '/trips/$tripId/packing'
    | '/trips/$tripId/preparing'
    | '/trips/$tripId/swipe'
    | '/store/$tripId'
    | '/trips/$tripId'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/product/$code'
    | '/store/$tripId'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/'
    | '/store/$tripId/ar'
    | '/store/$tripId/nav'
    | '/store/$tripId/scan'
    | '/trips/$tripId/edit'
    | '/trips/$tripId/packing'
    | '/trips/$tripId/preparing'
    | '/trips/$tripId/swipe'
    | '/store/$tripId/'
    | '/trips/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ProductCodeRoute: typeof ProductCodeRoute
  StoreTripIdRoute: typeof StoreTripIdRouteWithChildren
  TripsTripIdRoute: typeof TripsTripIdRouteWithChildren
  TripsNewRoute: typeof TripsNewRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$tripId': {
      id: '/store/$tripId'
      path: '/store/$tripId'
      fullPath: '/store/$tripId'
      preLoaderRoute: typeof StoreTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$code': {
      id: '/product/$code'
      path: '/product/$code'
      fullPath: '/product/$code'
      preLoaderRoute: typeof ProductCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/': {
      id: '/trips/$tripId/'
      path: '/'
      fullPath: '/trips/$tripId/'
      preLoaderRoute: typeof TripsTripIdIndexRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
    '/store/$tripId/': {
      id: '/store/$tripId/'
      path: '/'
      fullPath: '/store/$tripId/'
      preLoaderRoute: typeof StoreTripIdIndexRouteImport
      parentRoute: typeof StoreTripIdRoute
    }
    '/trips/$tripId/swipe': {
      id: '/trips/$tripId/swipe'
      path: '/swipe'
      fullPath: '/trips/$tripId/swipe'
      preLoaderRoute: typeof TripsTripIdSwipeRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
    '/trips/$tripId/preparing': {
      id: '/trips/$tripId/preparing'
      path: '/preparing'
      fullPath: '/trips/$tripId/preparing'
      preLoaderRoute: typeof TripsTripIdPreparingRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
    '/trips/$tripId/packing': {
      id: '/trips/$tripId/packing'
      path: '/packing'
      fullPath: '/trips/$tripId/packing'
      preLoaderRoute: typeof TripsTripIdPackingRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
    '/trips/$tripId/edit': {
      id: '/trips/$tripId/edit'
      path: '/edit'
      fullPath: '/trips/$tripId/edit'
      preLoaderRoute: typeof TripsTripIdEditRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
    '/store/$tripId/scan': {
      id: '/store/$tripId/scan'
      path: '/scan'
      fullPath: '/store/$tripId/scan'
      preLoaderRoute: typeof StoreTripIdScanRouteImport
      parentRoute: typeof StoreTripIdRoute
    }
    '/store/$tripId/nav': {
      id: '/store/$tripId/nav'
      path: '/nav'
      fullPath: '/store/$tripId/nav'
      preLoaderRoute: typeof StoreTripIdNavRouteImport
      parentRoute: typeof StoreTripIdRoute
    }
    '/store/$tripId/ar': {
      id: '/store/$tripId/ar'
      path: '/ar'
      fullPath: '/store/$tripId/ar'
      preLoaderRoute: typeof StoreTripIdArRouteImport
      parentRoute: typeof StoreTripIdRoute
    }
  }
}

interface StoreTripIdRouteChildren {
  StoreTripIdArRoute: typeof StoreTripIdArRoute
  StoreTripIdNavRoute: typeof StoreTripIdNavRoute
  StoreTripIdScanRoute: typeof StoreTripIdScanRoute
  StoreTripIdIndexRoute: typeof StoreTripIdIndexRoute
}

const StoreTripIdRouteChildren: StoreTripIdRouteChildren = {
  StoreTripIdArRoute: StoreTripIdArRoute,
  StoreTripIdNavRoute: StoreTripIdNavRoute,
  StoreTripIdScanRoute: StoreTripIdScanRoute,
  StoreTripIdIndexRoute: StoreTripIdIndexRoute,
}

const StoreTripIdRouteWithChildren = StoreTripIdRoute._addFileChildren(
  StoreTripIdRouteChildren,
)

interface TripsTripIdRouteChildren {
  TripsTripIdEditRoute: typeof TripsTripIdEditRoute
  TripsTripIdPackingRoute: typeof TripsTripIdPackingRoute
  TripsTripIdPreparingRoute: typeof TripsTripIdPreparingRoute
  TripsTripIdSwipeRoute: typeof TripsTripIdSwipeRoute
  TripsTripIdIndexRoute: typeof TripsTripIdIndexRoute
}

const TripsTripIdRouteChildren: TripsTripIdRouteChildren = {
  TripsTripIdEditRoute: TripsTripIdEditRoute,
  TripsTripIdPackingRoute: TripsTripIdPackingRoute,
  TripsTripIdPreparingRoute: TripsTripIdPreparingRoute,
  TripsTripIdSwipeRoute: TripsTripIdSwipeRoute,
  TripsTripIdIndexRoute: TripsTripIdIndexRoute,
}

const TripsTripIdRouteWithChildren = TripsTripIdRoute._addFileChildren(
  TripsTripIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ProductCodeRoute: ProductCodeRoute,
  StoreTripIdRoute: StoreTripIdRouteWithChildren,
  TripsTripIdRoute: TripsTripIdRouteWithChildren,
  TripsNewRoute: TripsNewRoute,
  TripsIndexRoute: TripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
